"""Render the certification findings report.

The critical property: **the agent never writes a number into this report.**
The report generator takes the agent's findings — each of which is only a
`(requirement_id, root_cause, recommendation, disposition)` tuple — and
re-binds every quantitative fact (measured value, bound, evidence hash,
triage cluster) from the graded roll-up, by requirement ID. So a finding can
say *why*, but the *numbers* are structurally guaranteed to come from the
Sprint 7-11 evidence, not from the reasoning policy. Turning the LLM on or
off cannot move a single figure.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List

from .agent import AgentResult
from .tools import ToolContext


def _fmt_value(v, unit: str) -> str:
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, (int, float)):
        return f"{f'{v:.4g}'} {unit}".strip()
    return str(v)


def _decision(ctx: ToolContext) -> str:
    status = ctx.fleet_status()
    return {"BLOCKED": "NO-GO", "FINDINGS": "GO WITH FINDINGS",
            "GREEN": "GO"}.get(status, "INSUFFICIENT EVIDENCE")


def render_findings_report(result: AgentResult,
                           include_transcript: bool = True) -> str:
    ctx = result.ctx
    roll = ctx.rollup()
    all_r = roll.all_results()
    n_total = len(all_r)
    n_pass = sum(1 for r in all_r if ctx.is_pass(r))
    n_block = sum(1 for r in all_r if ctx.is_blocking(r))
    catalog_version = roll.catalog_version

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    decision = _decision(ctx)

    L: List[str] = []
    L.append("# Certification Findings Report")
    L.append("")
    L.append("*Generated by the Polaris Sprint 12 Agentic V&V Analyst — every "
             "figure below is bound from the graded Sprint 7-11 evidence, not "
             "authored by the agent.*")
    L.append("")
    L.append(f"- **Date:** {now}")
    L.append(f"- **Acceptance basis:** `{ctx.basis}`"
             + ("  *(tightened, hypothetical — not the ratified catalog)*"
                if ctx.basis != "baseline" else ""))
    L.append(f"- **Reasoning policy:** `{result.policy_name}` "
             f"({result.n_steps} steps, {ctx.tool_calls} tool calls, "
             f"stopped: {result.stopped_reason})")
    L.append(f"- **Requirements catalog:** v{catalog_version}")
    L.append(f"- **Requirements:** {n_pass}/{n_total} pass, {n_block} blocking")
    L.append("")
    L.append(f"## Decision: **{decision}**  (fleet status: {ctx.fleet_status()})")
    L.append("")
    if ctx.decision_rationale:
        L.append("> " + ctx.decision_rationale.replace("\n", "\n> "))
        L.append("")

    # -- Subsystem roll-up -----------------------------------------------------
    L.append("## Subsystem roll-up")
    L.append("")
    L.append("| Subsystem | Status | Pass | Fail |")
    L.append("|---|---|---|---|")
    for s in roll.by_subsystem:
        rs = ctx.subsystem_results(s)
        p = sum(1 for r in rs if ctx.is_pass(r))
        f = sum(1 for r in rs if not ctx.is_pass(r))
        L.append(f"| {s.value} | {ctx.subsystem_status(s)} | {p} | {f} |")
    L.append("")

    # -- Findings --------------------------------------------------------------
    L.append("## Findings")
    L.append("")
    if not ctx.findings:
        L.append("No findings — all graded requirements pass under the "
                 f"`{ctx.basis}` basis. Evidence hashes are recorded below for "
                 "the file.")
        L.append("")
    else:
        def _key(f):
            r = ctx.result_for(f.requirement_id)
            return (0 if (r and ctx.is_blocking(r)) else 1, f.requirement_id)
        for i, f in enumerate(sorted(ctx.findings, key=_key), 1):
            r = ctx.result_for(f.requirement_id)
            if r is None:
                continue
            v = ctx.view(r)
            tag = "🚫 BLOCKER" if v["blocking"] else f.disposition
            L.append(f"### F-{i:02d} · {f.requirement_id} — {v['title']}")
            L.append("")
            L.append(f"- **Disposition:** {tag} (severity {v['severity']})")
            L.append(f"- **Criterion:** `{v['measured_value']}` "
                     f"{v['operator']} `{v['bound']}` {v['unit']}  →  "
                     f"**{v['status']}**"
                     + (f"  *(catalog bound {v['catalog_bound']})*"
                        if v['bound'] != v['catalog_bound'] else ""))
            L.append(f"- **Measured:** {_fmt_value(v['measured_value'], v['unit'])}"
                     f" over {v['n_runs']} run(s)")
            clusters = {}
            for ev in r.evidence:
                if ev.triage_label:
                    clusters[ev.triage_label] = clusters.get(ev.triage_label, 0) + 1
            worst = ctx.worst_run(r)
            if clusters:
                cl = ", ".join(f"{k} (×{n})" for k, n in clusters.items())
                L.append(f"- **Anomaly cluster:** {cl}")
            if worst is not None:
                L.append(f"- **Worst run:** scenario `{worst.scenario}`"
                         + (f", seed {worst.seed}" if worst.seed is not None else "")
                         + (f", triaged `{worst.triage_label}`"
                            if worst.triage_label else "")
                         + f", value {_fmt_value(worst.value, v['unit'])}")
            L.append(f"- **Root cause (analyst):** {f.root_cause}")
            L.append(f"- **Recommendation (analyst):** {f.recommendation}")
            L.append(f"- **Evidence:** `{v['artefact']}`")
            L.append(f"- **Hash:** `{v['evidence_hash']}`")
            if v["note"]:
                L.append(f"- **Note:** {v['note']}")
            L.append("")

    # -- Evidence manifest -----------------------------------------------------
    L.append("## Evidence manifest (audit trail)")
    L.append("")
    L.append("| Requirement | Status | Value | Bound | Hash |")
    L.append("|---|---|---|---|---|")
    for r in sorted(all_r, key=lambda x: x.requirement.id):
        v = ctx.view(r)
        h = (v["evidence_hash"] or "")[:12]
        L.append(f"| {v['requirement_id']} | {v['status']} "
                 f"| {_fmt_value(v['measured_value'], v['unit'])} "
                 f"| {v['operator']} {v['bound']} | `{h}` |")
    L.append("")

    # -- Transcript ------------------------------------------------------------
    if include_transcript:
        L.append("## Agent reasoning transcript")
        L.append("")
        L.append("*The exact tool-call sequence the agent took. Because the "
                 "action space is closed over grounded tools, this is a "
                 "complete, replayable audit of how the report was produced.*")
        L.append("")
        L.append("```")
        for step in result.transcript:
            L.append(step.as_text())
        L.append("```")
        L.append("")

    L.append("---")
    L.append("*Engineering clarity for complex futures.*")
    return "\n".join(L)
